version: '3.8'

networks:
  app:
    name: app

services:
  nginx:
    image: crmsolucoes/nginx-stable-alpine:latest
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app

  php:
    image: crmsolucoes/php-fpm-8.0:latest
    container_name: php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - app

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - app

  artisan:
    image: crmsolucoes/php-fpm-8.0:latest
    container_name: artisan
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan"]
    networks:
      - app

  npm:
    image: node:latest
    container_name: npm
    volumes: 
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - app
